resource_group_name = "daa-adf-test-qa"
location = "EAST US 2"
environment = "qa"
account_tier = "Standard"
replication_type = "LRS"
#managed_identity = "daaadftestqa"
container_name = "input"
adf_name = "daa-adf-test-qa"
# github_account_name = ""
# github_branch_name = 
# github_url =
# repo_name =
# root_folder =
sql_name = "daaadftestqaaserver"
administrator_login_name = "daaqa"
administrator_login_password = "azure@123"
sql_datbase = "daaadfqaadatabase"
max_size_gb = 2
sku_name = "Basic"